CREATE DATABASE AUTO CHARACTER SET utf8;
GRANT ALL ON AUTO.* TO audi@localhost IDENTIFIED BY 'mersu';

USE AUTO;
CREATE TABLE malli(id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(1024));
INSERT INTO malli(name) VALUES ('X5');
INSERT INTO malli(name) VALUES ('A5');
INSERT INTO malli(name) VALUES ('R8');
SELECT * FROM malli;
